[2024-05-20T04:02:25.368+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T04:02:25.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:02:22.088142+00:00 [queued]>
[2024-05-20T04:02:25.392+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:02:22.088142+00:00 [queued]>
[2024-05-20T04:02:25.392+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T04:02:25.405+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 04:02:22.088142+00:00
[2024-05-20T04:02:25.410+0000] {standard_task_runner.py:63} INFO - Started process 128 to run task
[2024-05-20T04:02:25.413+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'manual__2024-05-20T04:02:22.088142+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1kzov2bk']
[2024-05-20T04:02:25.416+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask transformar_data
[2024-05-20T04:02:25.450+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:02:22.088142+00:00 [running]> on host a5a7be3e911e
[2024-05-20T04:02:25.510+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T04:02:22.088142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T04:02:22.088142+00:00'
[2024-05-20T04:02:25.512+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T04:02:26.055+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T04:02:26.055+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 33, in extract_transform
    stock['sector'] = '' if stock['sector'] is None else stock['sector']
TypeError: string indices must be integers
[2024-05-20T04:02:26.064+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=manual__2024-05-20T04:02:22.088142+00:00, execution_date=20240520T040222, start_date=20240520T040225, end_date=20240520T040226
[2024-05-20T04:02:26.072+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task transformar_data (string indices must be integers; 128)
[2024-05-20T04:02:26.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T04:02:26.126+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T04:02:26.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
