[2024-05-20T05:33:27.889+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T05:33:27.905+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T05:33:25.897424+00:00 [queued]>
[2024-05-20T05:33:27.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T05:33:25.897424+00:00 [queued]>
[2024-05-20T05:33:27.910+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T05:33:27.918+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 05:33:25.897424+00:00
[2024-05-20T05:33:27.922+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-05-20T05:33:27.924+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'manual__2024-05-20T05:33:25.897424+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzasej5zu']
[2024-05-20T05:33:27.925+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask transformar_data
[2024-05-20T05:33:27.953+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data manual__2024-05-20T05:33:25.897424+00:00 [running]> on host 8251e45c28eb
[2024-05-20T05:33:28.015+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T05:33:25.897424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T05:33:25.897424+00:00'
[2024-05-20T05:33:28.016+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T05:33:28.563+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T05:33:28.564+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 32, in extract_transform
    stock['sector'] = '' if stock['sector'] is None else stock['sector']
TypeError: string indices must be integers
[2024-05-20T05:33:28.570+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=manual__2024-05-20T05:33:25.897424+00:00, execution_date=20240520T053325, start_date=20240520T053327, end_date=20240520T053328
[2024-05-20T05:33:28.578+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task transformar_data (string indices must be integers; 70)
[2024-05-20T05:33:28.617+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T05:33:28.633+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T05:33:28.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
