[2024-05-20T05:28:53.576+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T05:28:53.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift scheduled__2024-05-20T04:00:00+00:00 [queued]>
[2024-05-20T05:28:53.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift scheduled__2024-05-20T04:00:00+00:00 [queued]>
[2024-05-20T05:28:53.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T05:28:53.617+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conexion_redshift> on 2024-05-20 04:00:00+00:00
[2024-05-20T05:28:53.621+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-05-20T05:28:53.623+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'conexion_redshift', 'scheduled__2024-05-20T04:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpoio0dju5']
[2024-05-20T05:28:53.624+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask conexion_redshift
[2024-05-20T05:28:53.660+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.conexion_redshift scheduled__2024-05-20T04:00:00+00:00 [running]> on host 8251e45c28eb
[2024-05-20T05:28:53.725+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='conexion_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T04:00:00+00:00'
[2024-05-20T05:28:53.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T05:28:54.375+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T05:28:54.375+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 46, in connect_redshift
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: fe_sendauth: no password supplied

[2024-05-20T05:28:54.383+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=conexion_redshift, run_id=scheduled__2024-05-20T04:00:00+00:00, execution_date=20240520T040000, start_date=20240520T052853, end_date=20240520T052854
[2024-05-20T05:28:54.393+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task conexion_redshift (connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: fe_sendauth: no password supplied
; 65)
[2024-05-20T05:28:54.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T05:28:54.458+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T05:28:54.462+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
