[2024-05-20T04:11:59.724+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T04:11:59.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:11:56.747916+00:00 [queued]>
[2024-05-20T04:11:59.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:11:56.747916+00:00 [queued]>
[2024-05-20T04:11:59.748+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T04:11:59.759+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 04:11:56.747916+00:00
[2024-05-20T04:11:59.764+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2024-05-20T04:11:59.766+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'manual__2024-05-20T04:11:56.747916+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmptihpsjxy']
[2024-05-20T04:11:59.768+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask transformar_data
[2024-05-20T04:11:59.802+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data manual__2024-05-20T04:11:56.747916+00:00 [running]> on host a5a7be3e911e
[2024-05-20T04:11:59.870+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T04:11:56.747916+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T04:11:56.747916+00:00'
[2024-05-20T04:11:59.871+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T04:12:00.431+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T04:12:00.431+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 36, in extract_transform
    if stock['isEtf'] is not None and stock['isFund'] is not None and stock['beta'] is not None and stock['country'] is not None:
TypeError: string indices must be integers
[2024-05-20T04:12:00.440+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=manual__2024-05-20T04:11:56.747916+00:00, execution_date=20240520T041156, start_date=20240520T041159, end_date=20240520T041200
[2024-05-20T04:12:00.449+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task transformar_data (string indices must be integers; 86)
[2024-05-20T04:12:00.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T04:12:00.477+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T04:12:00.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
