[2024-05-20T05:29:38.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T05:29:38.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift manual__2024-05-20T05:29:35.354455+00:00 [queued]>
[2024-05-20T05:29:38.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift manual__2024-05-20T05:29:35.354455+00:00 [queued]>
[2024-05-20T05:29:38.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T05:29:38.823+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conexion_redshift> on 2024-05-20 05:29:35.354455+00:00
[2024-05-20T05:29:38.827+0000] {standard_task_runner.py:63} INFO - Started process 79 to run task
[2024-05-20T05:29:38.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'conexion_redshift', 'manual__2024-05-20T05:29:35.354455+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxou9qpn9']
[2024-05-20T05:29:38.830+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask conexion_redshift
[2024-05-20T05:29:38.858+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.conexion_redshift manual__2024-05-20T05:29:35.354455+00:00 [running]> on host 8251e45c28eb
[2024-05-20T05:29:38.910+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='conexion_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T05:29:35.354455+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T05:29:35.354455+00:00'
[2024-05-20T05:29:38.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T05:29:39.604+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T05:29:39.604+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 46, in connect_redshift
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: fe_sendauth: no password supplied

[2024-05-20T05:29:39.611+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=conexion_redshift, run_id=manual__2024-05-20T05:29:35.354455+00:00, execution_date=20240520T052935, start_date=20240520T052938, end_date=20240520T052939
[2024-05-20T05:29:39.619+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task conexion_redshift (connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: fe_sendauth: no password supplied
; 79)
[2024-05-20T05:29:39.643+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T05:29:39.661+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T05:29:39.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
